name: CA Tests

on: [push, pull_request]

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml
    with:
      key_container: ca
    secrets: inherit

  ca-basic-test:
    name: Basic CA
    needs: call-build-workflow
    uses: ./.github/workflows/ca-basic-test.yml
    with:
      os: ${{ matrix.os }}

  ca-ecc-test:
    name: CA with ECC
    needs: call-build-workflow
    uses: ./.github/workflows/ca-ecc-test.yml
    with:
      os: ${{ matrix.os }}

  ca-rsa-pss-test:
    name: CA with RSA/PSS
    needs: call-build-workflow
    uses: ./.github/workflows/ca-rsa-pss-test.yml
    with:
      os: ${{ matrix.os }}

  ca-existing-certs-test:
    name: CA with existing certs
    needs: call-build-workflow
    uses: ./.github/workflows/ca-existing-certs-test.yml
    with:
      os: ${{ matrix.os }}

  ca-existing-nssdb-test:
    name: CA with existing NSS database
    needs: call-build-workflow
    uses: ./.github/workflows/ca-existing-nssdb-test.yml
    with:
      os: ${{ matrix.os }}

  ca-existing-ds-test:
    name: CA with existing DS
    needs: call-build-workflow
    uses: ./.github/workflows/ca-existing-ds-test.yml
    with:
      os: ${{ matrix.os }}

  ca-shared-token-test:
    name: CA with shared token
    needs: call-build-workflow
    uses: ./.github/workflows/ca-shared-token-test.yml
    with:
      os: ${{ matrix.os }}

  ca-hsm-test:
    name: CA with HSM
    needs: call-build-workflow
    uses: ./.github/workflows/ca-hsm-test.yml
    with:
      os: ${{ matrix.os }}

  ca-container-test:
    name: CA container
    needs: call-build-workflow
    uses: ./.github/workflows/ca-container-test.yml
    with:
      os: ${{ matrix.os }}

  subca-basic-test:
    name: Basic Sub-CA
    needs: call-build-workflow
    uses: ./.github/workflows/subca-basic-test.yml
    with:
      os: ${{ matrix.os }}

  subca-cmc-test:
    name: Sub-CA with CMC
    needs: call-build-workflow
    uses: ./.github/workflows/subca-cmc-test.yml
    with:
      os: ${{ matrix.os }}

  subca-external-test:
    name: Sub-CA with external cert
    needs: call-build-workflow
    uses: ./.github/workflows/subca-external-test.yml
    with:
      os: ${{ matrix.os }}
