name: Code Analysis
on: [push, pull_request]

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  get-pr-ref:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
    name: Sonar cloud PR fork analyses deferring
    runs-on: ubuntu-latest
    steps:
      - name: Save PR information
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
          echo ${{ github.event.pull_request.base.ref }} > ./pr/BaseBranch

      - name: Upload pr as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr/

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          ignore_paths: tests # Don't check legacy test scripts

  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@v3.41.0
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1

