name: Python Tests

on: [push, pull_request]

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml
    with:
      key_container: tools
    secrets: inherit

  lint-test:
    name: Running Python lint
    needs: [call-build-workflow]
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    strategy:
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Retrieve runner image
        uses: actions/cache@v3
        with:
          key: pki-python-runner-${{ matrix.os }}-${{ github.run_id }}
          path: pki-python-runner.tar

      - name: Load runner image
        run: docker load --input pki-python-runner.tar

      - name: Run container
        run: |
          tests/bin/runner-init.sh pki
        env:
          HOSTNAME: pki.example.com

      - name: Run Python lint
        run: docker exec pki /usr/share/pki/tests/bin/pki-lint
