name: Python Tests

on: [push, pull_request]

jobs:
  test:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run Python lint
        run: |
          pylint-3 --version
          python3-flake8 --version
          /usr/share/pki/tests/bin/pki-lint
