name: Python Tests

on: [push, pull_request]

jobs:
  test:
    name: Pylint
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install linters
        run: |
          pip install pylint flake8

      - name: Run linters
        run: |
          pylint --version
          flake8 --version
          /usr/share/pki/tests/bin/pki-lint
